### ISSUE TITLE
Website Files Missing

### ISSUE THREAD

**Issue by mlin12321** [web-arena-x/visualwebarena#29]
Hello, 

I was wondering if all of the website pages were included in the google drive downloads for the visual web arena environments set up? For One Stop shop it only displays a total of 24 items (and no items under the category tab), at least for me.

**Comment by kohjingyu** [comment]
Yes, if you follow the [setup instructions exactly](https://github.com/web-arena-x/visualwebarena/blob/main/environment_docker/README.md) it should have the full environment by the end of it.

**Comment by mlin12321** [comment]
I am still encountering the same error as above when trying to set up the shopping website, despite my best efforts. Could you confirm that the attached tar file and commands to run the environment will fully set up the shopping website in a fresh environment (and should contain > 24 items)?

**Comment by vardaan123** [comment]
I am facing a similar issue (see attached screenshot). There are no items in 
Home -> Sports & Outdoors -> Hunting & Fishing -> Shooting 

<img width="1422" alt="image" src="https://github.com/web-arena-x/visualwebarena/assets/17354381/cc579608-4968-428f-ab0a-81c6b189b971">
and similarly for 
Home -> Clothing, Shoes & Jewelry -> Men -> Clothing 
Basically, no items to shop except those visible on homepage. Is this the expected behavior?

**Comment by kohjingyu** [comment]
It is not expected. If you download the file from Google Drive and run all the commands in the order specified, you should have the full catalog. You can confirm by checking the size of the downloaded file, it should be fairly large (~64G).

**Comment by mlin12321** [comment]
Issue still persists even with reinstalling the google drive file
