### ISSUE TITLE
How to navigate to www.homepage.com?

### ISSUE THREAD

**Issue by leoozy** [web-arena-x/visualwebarena#34]
Thank you for your work. I can come to the the homepage with http://127.0.0.1:4399 but not the www.homepage.com. Do I have to change the host of my server ot navigate to www.homepage.com?

**Comment by kohjingyu** [comment]
Because of [URL_MAPPINGS](https://github.com/web-arena-x/visualwebarena/blob/main/browser_env/env_config.py#L58), whenever the agent outputs http://homepage.com, it will [automatically map](https://github.com/web-arena-x/visualwebarena/blob/b6c9b643c430ea6fdc253e1cc02aa66223d4c57f/agent/prompts/prompt_constructor.py#L123) to the url set as the HOMEPAGE env variable.

**Comment by leoozy** [comment]
Thank you for your reply. I have another question about the prompt. When evaluating the CogVLM model under the image_som setting, do you insert the image-text examples into the prompt? Because CogVLM does not support multiple image input now.

**Comment by leoozy** [comment]
By the way, it seems that the password.html is missing
